image: maven:3.9.6-eclipse-temurin-21


pipelines:
  default:
    - step:
        name: Build artifact
        caches:
          - maven
        script:
          - mvn clean package
          - echo "Pipelines is running!"
        artifacts:
          - target/monolito-0.0.1-SNAPSHOT.jar
    - step:
        name: Deploy to S3
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: 'solvtreds-mono-service'
              LOCAL_PATH: 'target'
              #ACL: 'public-read'