version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: solvtrends
    image: solvtrends
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/solvtrends
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=solvtrends
      - POSTGRES_DB=solvtrends